#!/bin/bash

# Define formatting variables
GREEN='\033[1;32m'
NC='\033[0m' # No Color
GLYPH='󰏘'

# Execute other commands

# echo -e "\n${GREEN}${GLYPH} Running colors-foot.py ${NC}"
# python ~/.config/hypr/scripts/colors-foot.py

echo -e "\n${GREEN}${GLYPH} Running colors script (for hyprlock, lock screen) ${NC}"
~/.config/hypr/scripts/colors

echo -e "\n${GREEN}${GLYPH} Aplying hyprland colors (for window borders) ${NC}"
python ~/.config/hypr/scripts/colors-hypr.py

echo -e "\n${GREEN}${GLYPH} Running colors-folders.py (for papirus colored folders).${NC}"
python ~/.config/hypr/scripts/colors-folders.py

echo -e "\n${GREEN}${GLYPH} Generating rofi colors ${NC}"
python ~/.config/hypr/scripts/rofi-colors.py

echo -e "\n${GREEN}${GLYPH} changing spotiify theme (text) ${NC}"
pywal-spicetify text
# spicetify apply

echo -e "\n${GREEN}${GLYPH} Running walogram (for telegram) ${NC}"
walogram -s

echo -e "\n${GREEN}${GLYPH} Running pywal-discord (for discord) ${NC}"
pywal-discord -p ~/.config/vesktop/themes/

echo -e "\n${GREEN}${GLYPH} Running zed-theme (for Zed) ${NC}"
~/.config/hypr/scripts/zed-theme

echo -e "\n${GREEN}${GLYPH} Script execution completed.${NC}"
